logging:
  level:
    org.oome: debug

spring:
  config:
    import:
      - classpath:local/application-api.yml
      - classpath:local/application-db.yml
      - classpath:local/application-web.yml
    activate:
      on-profile: local