org:
  oome:
    root-url: http://localhost:8080
    api:
      version:
        common: v1
        qna: v1
        blog: v1
        util: v1
        ext: v1
      context-path:
        is-use: true
        common-url: /api/${org.oome.api.version.common}/common
        qna-url: /api/${org.oome.api.version.qna}/qna
        blog-url: /api/${org.oome.api.version.blog}/blog
        util-url: /api/${org.oome.api.version.util}/util
        ext-url: /api/${org.oome.api.version.ext}/ext

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher