spring:
  datasource:
    url: jdbc:log4jdbc:mysql://34.64.157.74:3306/oome
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: oome123!@#

  jpa:
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  redis:
    host: 34.168.141.30
    port: 6379
